[package]
name = "napi-rs-revm-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
eyre = "0.6.12"
revm = "33.1.0"
serde = "1.0"
serde_json = "1.0"
hex = "0.4"
